### ISSUE TITLE
Consider adding a linter/typescript?

### ISSUE THREAD

**Issue by noblica** [bitwave-tv/bitwave#123]
Hey, this might be less of an "issue" and more of a question regarding the codebase. I was looking at the code a little bit, and was wondering, have you considered adding a linter, or maybe adding typescript to improve code quality/robustness?

**Comment by DispatchCommit** [comment]
I'd like to move the project to typescript with Nuxt typescript (https://typescript.nuxtjs.org/) but there is a fairly limiting bug / issue with the dev builds that I'm hoping are resolved prior to conversion.

https://github.com/nuxt/nuxt.js/issues/6442

Last time I began the conversion I ran into the issue above, should probably give it another shot since it's been a few months since my last investigation into the typescript conversion.

**Comment by noblica** [comment]
Seems like the issue still persists, sadly. But I'm a bit confused, is it related to TypeScript? Seems like a general issue with HMR, regardless of TS.

**Comment by DispatchCommit** [comment]
It *is* a more general issue (and yes, related to HMR), but it's an issue that I currently have managed to avoid in the project's current state, but switching to TS was re-introducing the bug sadly.
I'll try adding it again tonight and update.
